In [ ]:
DATASET SUMMARY REPORT - DAY7

## 1. Import Pandas and Load the Dataset

In [2]:
import pandas as pd

df = pd.read_csv("Day7_Student_Dataset.csv")

print("Dataset loaded successfully!")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Dataset loaded successfully!
Rows: 25
Columns: 7

## 2. Inspect the First Few Rows

`head()` displays the first five rows

In [3]:
df.head()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow

## 3. Inspect the Last Few Rows

`tail()` displays the last five rows

In [4]:
df.tail()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

## 4. View Random Samples

`sample()` helps us inspect randomly selected records

In [5]:

df.sample(5, random_state=42)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
11,1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi

## 5. Check the Dataset Shape

In [6]:
print("Shape:", df.shape)
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Shape: (25, 7)
Number of rows: 25
Number of columns: 7

## 6. View Column Names

The `columns` attribute shows all available features/variables in the dataset.

In [7]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage',
       'City'],
      dtype='object')

## 7. View the DataFrame Index

The `index` attribute shows the row labels used by the DataFrame.

In [8]:
df.index

RangeIndex(start=0, stop=25, step=1)

## 8. Check Data Types

`dtypes` shows the data type stored in each column.

In [9]:
df.dtypes

Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

## 9. Dataset Information with `info()`

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB

## 10. Descriptive Statistics with `describe()`

`describe()` summarizes the numerical columns using statistics such as count, mean, standard deviation, minimum, quartiles, and maximum.

In [ ]:
df.describe()

## 11. Check for Missing Values

Missing values are checked column-by-column using `isna().sum()`.

In [11]:
missing_values = df.isna().sum()

print("Missing values in each column:")
display(missing_values)

print("\nTotal missing values:", missing_values.sum())

Missing values in each column:

Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

Total missing values: 3

## 12. Basic Dataset Observations

Based on the Pandas exploration above, the following observations can be made:

In [12]:
print(f"• The dataset contains {df.shape[0]} rows and {df.shape[1]} columns.")
print(f"• The available features are: {', '.join(df.columns)}.")
print("• Integer columns:", ", ".join(df.select_dtypes(include="int64").columns))
print("• Floating-point columns:", ", ".join(df.select_dtypes(include="float64").columns))
print("• Text/object columns:", ", ".join(df.select_dtypes(include="object").columns))

missing = df.isna().sum()
nonzero_missing = missing[missing > 0]

if len(nonzero_missing) == 0:
    print("• No missing values were found.")
else:
    print("• Missing values were found in:")
    for column, count in nonzero_missing.items():
        print(f"  - {column}: {count} missing value(s)")

print(f"• The average age is {df['Age'].mean():.2f} years.")
print(f"• The average marks value is {df['Marks'].mean():.2f} (calculated from non-missing values).")
print(f"• The average attendance is {df['Attendance_Percentage'].mean():.2f}% (calculated from non-missing values).")
print(f"• The dataset contains {df['Course'].nunique()} unique courses and {df['City'].nunique()} unique cities.")

• The dataset contains 25 rows and 7 columns.
• The available features are: Student_ID, Name, Age, Course, Marks, Attendance_Percentage, City.
• Integer columns: Student_ID, Age
• Floating-point columns: Marks, Attendance_Percentage
• Text/object columns: Name, Course, City
• Missing values were found in:
  - Marks: 1 missing value(s)
  - Attendance_Percentage: 1 missing value(s)
  - City: 1 missing value(s)
• The average age is 20.00 years.
• The average marks value is 82.25 (calculated from non-missing values).
• The average attendance is 87.08% (calculated from non-missing values).
• The dataset contains 3 unique courses and 13 unique cities.